name: default-environment
channels:
  - emscripten-forge
  - conda-forge
dependencies:
  # A Jupyter kernel for Python
  - xeus-python
  - numpy
  - pandas
  - matplotlib
  - scipy
  # - jupyterlab-slideshow # required httpcore
  - pip:
    - laby-jupyter-python
    - jupyterlab-myst >= 2.6 # depends on jupyter-server if specified as conda package
